# .github/workflows/deploy.yml
name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        # or
        # run: yarn install

      - name: Build project
        run: npm run build
        # or
        # run: yarn build

      - name: Deploy
        run: npm run deploy
        # Customize this part based on your deployment strategy
        # For example, if deploying to Vercel, you might run:
        # run: vercel --prod
